### ISSUE TITLE
Messaging Error

### ISSUE THREAD

**Issue by Cyber56** [surfranch/TelegramShillBot#13]
Can you make the code have message error? The bot message us if the code stopped or have problem to notify us.

**Comment by gfirst20** [comment]
i have done most things until the final step to run the python script. this is what i got

Traceback (most recent call last):
  File "tg_shill_bot.py", line 260, in <module>
    CLIENT = TelegramClient(APP_SHORT_NAME, API_ID, API_HASH)
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/telegrambaseclient.py", line 299, in __init__
    self.api_id = int(api_id)
ValueError: invalid literal for int() with base 10: '1d491ef9d3521e4be434f0483d6a6d60'




help  me fix please

**Comment by gkspranger** [comment]
not at this time
