### ISSUE TITLE
Correctly terminate Bot and session

### ISSUE THREAD

**Issue by netquik** [surfranch/TelegramShillBot#3]
Hi All.
I'm asking if is there a way to correctly terminate the bot along with the telegram session.
I found that stopping the container in Docker seems not to close the telegram session in telegram.
Thanks.

**Comment by netquik** [comment]
Should we use log_out() / stop() on KeyboardInterrupt ?

**Comment by gkspranger** [comment]
thanks for the info @netquik 

just got around to working on this and am testing this commit now :: https://github.com/surfranch/TelegramShillBot/commit/69a01109ff693a39d2a8f904e24eba3d299562a1

if all good on my end, will merge into main branch soon

thanks

**Comment by gkspranger** [comment]
merged a potential fix :: https://github.com/surfranch/TelegramShillBot/pull/11
