### ISSUE TITLE
Text formatting

### ISSUE THREAD

**Issue by gfirst20** [surfranch/TelegramShillBot#32]
How can i format text better. 

if i push to next line, it doesnt work, so i use only spaces. how can i format message text to next line

**Comment by gfirst20** [comment]
--- 
api_hash: *************************
api_id: *********
app_short_name: ******
messages: 
  four: "✊✊✊The HODLHands NFT clenched raised first is a symbol of Unity, Strength, & Resistance ✊✊✊HODL - “To Hold On For Dear Life. To never sell. Hold your bag through ups & downs in the market” ✊✊✊ Check ** hodltoken . net / nft ** to mint yours quickly ✊✊✊"
  one: "🤩🤩🤩HODL2.0 🤩🤩🤩🤩 NFTS LAUNCHED ON SALE 🤩🤩🤩 HODL dash board Launched  🤩🤩🤩 New DOXXED CEO 🤩🤩🤩 BNB REWARD TOKEN 🤩🤩🤩 Gamification coming! 🤩🤩🤩 PUMPING NOW!!!!! 🤩🤩🤩 Invest In HODL 2.0 NOW!!! 🤩🤩🤩 GIVEAWAYS ON TG ** Telegram: @ hodlinvestorgroup ** 🤩🤩🤩 "
  three: "✊✊✊ HODLHANDS NFT Collection just launched for a floor price of 0.045 ETH and it's selling out pretty fast. ✊✊✊ Special ones will give access to Special reward features on the HODLTOKEN ecosystem. ✊✊✊ Grab yours now before it gets sold out.✊✊✊ Check ** hodltoken . net / nft ** to mint yours quickly ✊✊✊"
  two: "😎 HODL 2.0 😎     ⬆️ COLLECT BNB REWARDS AND REFLECTIONS DAILY!!!! 🚀😎🎉👀 💰     HUGE BUYING OPPORTUNITY 🛎     ✅ LISTED ON CMC     ✅ AUDIT COMPLETE     ✅ SHOWING ON COINBASE     ✅ LISTED ON BITMART     ✅ LISTED ON DECOIN     ✅ LISTED ON LBANK      ✅ LISTED ON FEGEX      ✅ LISTED ON SAFEDEX      🔥5 exchanges already listed  3 within 1 month of launch!!! 🚀      CONTINUOUSLY INNOVATING AND UPGRADING LFG!!! 🚀🚀🚀        Contract: 0x5788105375ecf7f675c29e822fd85fcd84d4cd86   ** Telegram: hodlinvestorgroup  Website: Hodltoken dot net ** "
phone_number: "+***********"
raid: 
  ShillYourGems: 
    image: images/hh5.png
    increase_wait_interval: 1
    message_type: 
      - one
      - two
      - three
      - four
    wait_interval: 61

**Comment by gkspranger** [comment]
i believe this to be a config issue .. follow the README closely and you should be AOK

```yaml
# your config, which will not respect new lines
messages:
  one: "this is my message this should be a new line"

# how it should be
messages:
  one: |
    this is my message
    this should be a new line
```

**Comment by gfirst20** [comment]
worked. thank you
