### ISSUE TITLE
ResolveUsernameRequest Wait Limitation

### ISSUE THREAD

**Issue by netquik** [surfranch/TelegramShillBot#4]
Considering these API limitations/errors:

1. Waiting for A wait of X seconds is required (caused by ResolveUsernameRequest)

or

2. FloodWaitError invoked; Forced waiting for A wait of X seconds is required (caused by ResolveUsernameRequest)

Is there a solution for ResolveUsernameRequest API pseudo-ban?
what causes this restriction?
In the second case I see that it is a subsequent ban not detected during use. But only on the next start.
Thanks

**Comment by gkspranger** [comment]
we think this PR should fix the issue :: https://github.com/surfranch/TelegramShillBot/pull/9
