### ISSUE TITLE
Getting this error. Please help. Thanks

### ISSUE THREAD

**Issue by thejunaidkazi** [surfranch/TelegramShillBot#7]
Getting this error after doing almost everything mentioned in the readme doc. 
![Uploading error.jpg…]()

**Comment by thejunaidkazi** [comment]
Getting this error after doing almost everything mentioned in the readme doc.
![error](https://user-images.githubusercontent.com/87858172/134429613-3b98e925-5797-4bd4-87bd-1fe3e00f7857.jpg)

**Comment by gkspranger** [comment]
hi @thejunaidkazi 

it appears you missed the step of setting up your environment and/or "activating" said environment :: https://github.com/surfranch/TelegramShillBot#not-as-easy

we do recommend you consider running via docker as it is the one most likely to work on your machine

thanks

**Comment by thejunaidkazi** [comment]
Docker gives a Microsoft frame work error. So i can't even initiate docker.
